---
title: "Focal_Activity_Budget"
author: "Allegra DePasquale"
date: "5/29/2020"
output: html_document
---

#This script analyses foraging activity budget based on 2019 paired focal follows

library(ggpubr)

```{r}


#Reading in .csvs that contains duration for all states, focal pair info, group info, cv phenotype info, dominance info, reproductive status info, weather and fruit biomass info

df_duration_1 <- read.csv("Foraging_State_Duration.csv")
df_pair <- read.csv("pair_ID.csv")
df_group <- read.csv("group_iD.csv")
df_phenotype <- read.csv("focal_phenotypes.csv")
df_dom <- read.csv("dom_2019.csv")
df_rs <- read.csv("reproductivestatus_2019.csv")
df_weather <- read.csv("Weather_For_Allegra_2019.csv")
df_biomass <- read.csv("monthly_fruit_biomass.csv")


#Setting DateTime in df_duration_1 as a Date
df_duration_1$DateTime <- parse_date_time(df_duration_1$DateTime, orders = "mdy")
df_duration_1 <- df_duration_1 %>% mutate(DateTime = as_datetime(DateTime))
df_duration_1$DateTime <- as.Date(df_duration_1$DateTime)

#Setting duration as seconds
df_duration_1$Duration <- lubridate::hms(df_duration_1$Duration)
df_duration_1$Duration <- as.numeric(df_duration_1$Duration)


#Renaming ID column 
df_duration_1 <- df_duration_1 %>% 
           rename(
           Focal = ï..ID,
   
                         )

#Excluding OOS time
df2 <- df_duration_1[df_duration_1$State != "OOS",]   

df3 <- df2 %>% 
  group_by(Focal, DateTime, Animal, State) 

#Counting bites per foraging state for each focal
df3 <- df3 %>%  summarise(DurationTotal=sum(Duration))

#Making bites per foraging state their own column
df3 <- df3 %>% spread(State, DurationTotal)
df_long <- df3

#Excluding focal with Ducky, and focal 226 with PR, since these were purposefully recorded to capture pith bites
df3 <- df3[!(df3$Animal == "DU") ,]
df3 <- df3[!(df3$Focal  == "226") ,]

#Setting NAs to zero

df3[c("EFI", "EFF", "FFL", "FUN", "FFR", "FIN", "FOT","RES", "SAC","TRA","VFO", "OTH", "SDI", "PLA", "SAG", "VIG", "DRI", "EXC", "SRE")][is.na(df3[c("EFI", "EFF", "FFL", "FUN", "FFR", "FIN", "FOT","RES", "SAC", "TRA","VFO", "OTH", "SDI", "PLA", "SAG", "VIG", "DRI","EXC", "SRE")])] <- 0


#Creating Total Duration and Total Foraging Duration columns

df4 <- df3 %>% mutate(TotalDuration = EFI + EFF + FFL + FUN + FFR + FIN + FOT + RES + SAC + TRA + VFO + OTH + SDI + PLA + SAG + VIG + DRI + EXC)

df5 <- df4 %>% mutate(TotalForagingDuration = EFI + EFF + FFL + FUN + FFR + FIN + FOT + VFO )


#Joining pair, group, cv phenotype

df5 <- df_pair %>% left_join(., df5, by = c("Animal" = "Animal"))                
df5 <- df_group %>% left_join(., df5, by = c("Animal" = "Animal"))  
df5<- df_phenotype %>% left_join(., df5, by = c("Animal" = "Animal")) 
df5 <- df_dom %>% left_join(., df5, by = c("Animal" = "Animal"))
df5 <- df5 %>%  fuzzy_left_join(., df_rs, by = c("Animal" = "Animal", "DateTime" = "StartDate", "DateTime" = "EndDate"), match_fun = list(`==`, `>=`, `<=`))  

df5 <- df5 %>%
                      dplyr::select(-Animal.y, -StartDate, -EndDate)  

#Renaming animal
df5<- df5 %>%
              rename(Animal = Animal.x)                                             

#Renaming scaled rank        
df5 <- df5 %>%
              rename(ScaledRank = Scaled.Rank)

#Renaming reproductive status
df5 <- df5 %>%
              rename(ReproductiveStatus = Reproductive.Status)


df5 <- df5 %>% left_join(., df_weather, by = c("DateTime" = "DateTime")) 
                                                         
#Adding month column to final_df to facilitate join with df_biomass
df5 <- df5 %>% mutate(Month = month(DateTime))
df5 <- df5 %>% left_join(., df_biomass, by = c("Month" = "Month")) 

#Renaming monthly fruit biomass
df5 <- df5  %>%
              rename(MonthlyFruitBiomass = Ripe.Fruit.Biomass)

#Recoding D and T (this recode function is from the package car)  
#df5$Phenotype <- Recode(df5$Phenotype, "'D'='Dichromat'; 'T'='Trichromat'")

#Setting scaled rank as an ordinal variable
df5$DominanceCategory <- if_else(df5$ScaledRank <= 0.33, "low", if_else(df5$ScaledRank > 0.33 & df5$ScaledRank <= 0.66, "mid","high"))  


#Z-transforming TempMax, TempMin, Rainfall, and Monthly Fruit Biomass
df5 <- df5 %>%
       mutate_at(vars("TempMax", "TempMin", "Rain", "MonthlyFruitBiomass"), list(~as.numeric(scale(.)))) 



ForagingTimeModel <- glmer(TotalForagingDuration ~  
                                Phenotype + 
                                DominanceCategory +
                                ReproductiveStatus +
                                TempMax +
                                TempMin +
                                Rain +
                                MonthlyFruitBiomass +
                                offset(log(TotalDuration)) + 
                                (1 | Group/Animal) + (1 | Pair),
                              data = df5,
                              family = poisson(link = "log"))          

drop1(ForagingTimeModel, test = "Chisq")



FruitTimeModel <- glmer(FFR ~  
                                Phenotype + 
                                DominanceCategory +
                                ReproductiveStatus +
                                TempMax +
                                TempMin +
                                Rain +
                                MonthlyFruitBiomass +
                                offset(log(TotalDuration)) + 
                                (1 | Group/Animal) + (1 | Pair),
                              data = df5,
                              family = poisson(link = "log"))          

drop1(FruitTimeModel, test = "Chisq")


InsectTimeModel <- glmer(FIN ~  
                                Phenotype + 
                                DominanceCategory +
                                ReproductiveStatus +
                                TempMax +
                                TempMin +
                                Rain +
                                MonthlyFruitBiomass +
                                offset(log(TotalDuration)) + 
                                (1 | Group/Animal) + (1 | Pair),
                              data = df5,
                              family = poisson(link = "log"))          

drop1(InsectTimeModel, test = "Chisq")

FOTTimeModel <- glmer(FOT ~  
                                Phenotype + 
                                DominanceCategory +
                                ReproductiveStatus +
                                TempMax +
                                TempMin +
                                Rain +
                                MonthlyFruitBiomass +
                                offset(log(TotalDuration)) + 
                                (1 | Group/Animal) + (1 | Pair),
                              data = df5,
                              family = poisson(link = "log"))          

drop1(FOTTimeModel, test = "Chisq")







```


```{r}
#Creating columns with collapsed behavioral states
dfg <- df5
dfg <- dfg %>% mutate(Social = SAG + SAC)
dfg <- dfg %>% mutate(Rest = RES + SRE)
dfg <- dfg %>% mutate(Other = OTH + EXC + PLA + SDI + DRI)
dfg <- dfg %>% mutate(TotalForaging = TotalForagingDuration)

dfg1 <- dfg %>% gather(State, Duration, TotalForaging, Social, Rest, Other, VFO, TRA, FIN, FFR, factor_key=TRUE)

dfg1 <- dfg1 %>%
                      dplyr::select( - SRE, -RES, -SAC, - OTH, -SDI, -PLA,-SAG,-DRI,-EXC, -ScaledRank, -DominanceCategory, -ReproductiveStatus, -Group, - TempMax, -TempMin, -Rain, -MonthlyFruitBiomass, -Month, -FUN, -FOT, -EFI, -EFF, -FFL, -VIG, -TotalForagingDuration)



ggplot(dfg1, aes(fill= Phenotype, y = log(Duration), x = State)) + 
    geom_boxplot() 




```

```{r}
#This chunk analyzes time spent conpsicuous fruit foraging


df_duration_taxon <- read.csv("Foraging_State_Duration_with_taxon.csv")
df_color <- read.csv("colors_final_final.csv")

df_duration_taxon$DateTime <- parse_date_time(df_duration_taxon$DateTime, orders = "mdy")
df_duration_taxon <- df_duration_taxon %>% mutate(DateTime = as_datetime(DateTime))
df_duration_taxon$DateTime <- as.Date(df_duration_taxon$DateTime)

#Setting duration as seconds
df_duration_taxon$Duration <- lubridate::hms(df_duration_taxon$Duration)
df_duration_taxon$Duration <- as.numeric(df_duration_taxon$Duration)

#Subsetting to just fruit foraging
df_duration_fruit <- df_duration_taxon[df_duration_taxon$State == "FFR",] 


#Reading in and joining.csv that contains color classifications for all fruit
df_color <- read.csv("colors_final_final.csv")
df_duration_fruit <- df_duration_fruit %>% left_join(., df_color, by = c("Taxon" = "Taxon" 
))

#Subsetting to bouts of ffr with known color cats
df_duration_fruit <- df_duration_fruit[df_duration_fruit$ColourCategory == "con" |df_duration_fruit$ColourCategory == "cry" | df_duration_fruit$ColourCategory == "dark"| df_duration_fruit$ColourCategory == "con_both",]

#Renaming ID column 
df_duration_fruit <- df_duration_fruit %>% 
           rename(
           Focal = ID,
   
                         )

#Grouping by variables Focal, Animal, State, and Behavior
df_duration_fruit1 <- df_duration_fruit %>% 
  group_by(Focal, DateTime, Animal, ColourCategory) 

#Counting bites per foraging state for each focal
df_duration_fruit2 <- df_duration_fruit1 %>%  summarise(DurationTotal=sum(Duration))

#Making bites per foraging state their own column
df_duration_fruit3 <- df_duration_fruit2 %>% spread(ColourCategory, DurationTotal)

#Excluding focal with Ducky and focal 226 which was PR eating pith
df_duration_fruit3 <- df_duration_fruit3[!(df_duration_fruit3$Animal == "DU") ,]
df_duration_fruit3 <- df_duration_fruit3[!(df_duration_fruit3$Focal  == "226") ,]

#Setting NAs to zero

df_duration_fruit3[c("con", "con_both", "cry", "dark")][is.na(df_duration_fruit3[c("con", "con_both", "cry", "dark")])] <- 0

#Joining pair, group, cv phenotype

df_duration_fruit3 <- df_pair %>% left_join(., df_duration_fruit3, by = c("Animal" = "Animal"))                
df_duration_fruit3  <- df_group %>% left_join(., df_duration_fruit3, by = c("Animal" = "Animal"))  
df_duration_fruit3 <- df_phenotype %>% left_join(., df_duration_fruit3, by = c("Animal" = "Animal")) 
df_duration_fruit3  <- df_dom %>% left_join(., df_duration_fruit3, by = c("Animal" = "Animal"))
df_duration_fruit3  <- df_duration_fruit3  %>%  fuzzy_left_join(., df_rs, by = c("Animal" = "Animal", "DateTime" = "StartDate", "DateTime" = "EndDate"), match_fun = list(`==`, `>=`, `<=`))  

df_duration_fruit3 <- df_duration_fruit3 %>%
                      dplyr::select(-Animal.y, -StartDate, -EndDate, - "<NA>")  

#Renaming animal
dfdf <- df_duration_fruit3 %>%
              rename(Animal = Animal.x)                                             

#Renaming scaled rank        
dfdf <- dfdf %>%
              rename(ScaledRank = Scaled.Rank)

#Renaming reproductive status
dfdf <- dfdf %>%
              rename(ReproductiveStatus = Reproductive.Status)


dfdf <- dfdf %>% left_join(., df_weather, by = c("DateTime" = "DateTime")) 
                                                         
#Adding month column to final_df to facilitate join with df_biomass
dfdf <- dfdf %>% mutate(Month = month(DateTime))
dfdf <- dfdf %>% left_join(., df_biomass, by = c("Month" = "Month")) 

#Renaming monthly fruit biomass
dfdf <- dfdf  %>%
              rename(MonthlyFruitBiomass = Ripe.Fruit.Biomass)

#Recoding D and T (this recode function is from the package car)  
#df5$Phenotype <- Recode(df5$Phenotype, "'D'='Dichromat'; 'T'='Trichromat'")

#Setting scaled rank as an ordinal variable
dfdf$DominanceCategory <- if_else(dfdf$ScaledRank <= 0.33, "low", if_else(dfdf$ScaledRank > 0.33 & dfdf$ScaledRank <= 0.66, "mid","high"))  


#Z-transforming TempMax, TempMin, Rainfall, and Monthly Fruit Biomass
dfdf <- dfdf %>%
       mutate_at(vars("TempMax", "TempMin", "Rain", "MonthlyFruitBiomass"), list(~as.numeric(scale(.)))) 

#Extracting TotalDuration column for use in dfdf
df_select <- df5 %>% select(Focal, TotalDuration)

dfdf <- dfdf %>% left_join(., df_select, by = c("Focal" = "Focal")) 


#Modeling conspicuous fruit foraging time

ConspicuousFruitTimeModel <- glmer(con ~  
                                Phenotype + 
                                DominanceCategory +
                                ReproductiveStatus +
                                TempMax +
                                TempMin +
                                Rain +
                                MonthlyFruitBiomass +
                                offset(log(TotalDuration)) + 
                                (1 | Group/Animal) + (1 | Pair),
                              data = dfdf,
                              family = poisson(link = "log"))     

drop1(ConspicuousFruitTimeModel, test = "Chisq")

ConspicuousFruitTimeModel.emm <- emmeans(ConspicuousFruitTimeModel, "Phenotype", type = "response", adjust = "tukey") #This function displays the LSM


pairs(emmeans(ConspicuousFruitTimeModel, "Phenotype", adjust = "tukey"))



ConspicuousFruitTimeModel.emm.cld.tukey <- cld.emmGrid(ConspicuousFruitTimeModel.emm, alpha = 0.05, Letters = letters, adjust = "tukey") #This function creates a compact letter display of the LSM enabling use with ggplot. It also adds a Tukey adjustment to test for honest significant difference between the means.


ConFruitTime <- ConspicuousFruitTimeModel.emm.cld.tukey



dfdfg <- dfdf %>% gather(ColourCategory, Duration, con, con_both, cry, dark, factor_key=TRUE)

dfdfg <- dfdfg %>%
                      dplyr::select( -ScaledRank, -DominanceCategory, -ReproductiveStatus, -Group, - TempMax, -TempMin, -Rain, -MonthlyFruitBiomass, -Month)


ggplot(dfdfg, aes(fill= Phenotype, y = log(Duration), x = ColourCategory)) + 
    geom_boxplot() 




taxa <- as.data.frame(unique(df_duration_taxon$Taxon))
```


