---
title: "GLMMs_AmNat_Revised"
author: "Allegra DePasquale"
date: "9/22/2022"
output: html_document
---
###BITE COUNT ANALYSIS
```{r}
#Loading dependencies
library(lme4)
library(emmeans)
library(tidyverse)
library(ggpubr)


###Reading in csv
df_bite_final <- read.csv("Complete_Bite_DF_July_1_2022.csv")

#Re-leveling taxon
df_bite_final$TaxonNEW <- factor(df_bite_final$TaxonNEW, levels = c("HIVE", "ANTS", "FIN", "LGRA", "CATA","EFI", "FCOT", "GMAC", "BPOL", "GAME", "SOBO",  "PPLA", "QOLE", "MTIN", "CVER"))


#Running bite count neg bin glmm
BiteCountModel <- glmer.nb(Count ~  
                                Phenotype*TaxonNEW*FruitBiomassCategory +
                                DominanceCategory +
                                offset(log(Duration)) +
                                (1 | Animal) +
                                (1 | Pair), 
                                data = df_bite_final, control=glmerControl(optCtrl=list(maxfun=2e4)))


#Getting model summary
summary(BiteCountModel)
overdisp_fun(BiteCountModel)

#Planned pairwise comparisons 
Bite.emm <- emmeans(BiteCountModel, pairwise ~  Phenotype | TaxonNEW | FruitBiomassCategory, type = "response", adjust = "tukey")

#Putting EMMs in df for use in ggplot2
BitePlot_freq <- emmip(BiteCountModel, ~ Phenotype | TaxonNEW | FruitBiomassCategory, type = "response", plotit = FALSE) 

#Reading in color variable for plotting
df_color_cat_new <- read.csv("ColourCategoriesBroadFeb102022.csv")

#Renaming TaxonNEW variable
df_color_cat_new <- df_color_cat_new %>% 
           rename(
           TaxonNEW = ï..TaxonNEW,
   
                         )

#Joining EMM df with broad food categories for plotting
BitePlot_freq <- df_color_cat_new %>% left_join(., BitePlot_freq, by = c( 
                                                            "TaxonNEW" = "TaxonNEW"))

#Joining color category df to bite df
df_final <- df_color_cat_new %>% left_join(., df_bite_final, by = c( 
                                                            "TaxonNEW" = "TaxonNEW"))

#Removing 2 outliers in raw data for visualization
df_final <- df_final[!(df_final$State == "EFI" & df_final$Count > 200),]
df_final <- df_final[!(df_final$State == "FIN" & df_final$Count > 200),]

#Setting as factor
BitePlot_freq$TaxonNEW <- as.factor(BitePlot_freq$TaxonNEW)

#Recoding factor in EMM df
BitePlot_freq$TaxonNEW <- recode_factor(BitePlot_freq$TaxonNEW, HIVE = "Extracted wasp larvae", EFI = "Extracted invertebrates", ANTS = "Extracted ants",  FIN = "Gleaned invertebrates",  LGRA = "Gleaned large grasshopper", CATA = "Gleaned caterpillar", FCOT = "Ficus cotinifolia", GMAC = "Guettarda macrosperma", BPOL = "Bunchosia polystachia", GAME = "Genipa americana", SOBO = "Stemmadenia obovata", PPLA = "Passiflora platyloba", QOLE = "Quercus oleoides", MTIN  = "Maclura tinctoria", CVER = "Cissus verticillata")

#Recoding factor in bite df

df_final$TaxonNEW <- recode_factor(df_final$TaxonNEW, HIVE = "Extracted wasp larvae", EFI = "Extracted invertebrates", ANTS = "Extracted ants",  FIN = "Gleaned invertebrates",  LGRA = "Gleaned large grasshopper", CATA = "Gleaned caterpillar", FCOT = "Ficus cotinifolia", GMAC = "Guettarda macrosperma", BPOL = "Bunchosia polystachia", GAME = "Genipa americana", SOBO = "Stemmadenia obovata", PPLA = "Passiflora platyloba", QOLE = "Quercus oleoides", MTIN  = "Maclura tinctoria", CVER = "Cissus verticillata")


#Plotting EMMs and raw data
BiteFreqPlot <- ggplot(BitePlot_freq, aes(x = TaxonNEW, y = yvar, color =   
  Phenotype)) +
  geom_point(size = 2, position=position_dodge(width=0.5)) +
  geom_point(data = df_final, aes(x = TaxonNEW, y = Count, color = Phenotype), alpha = 0.2, position = "jitter") +
  scale_shape_manual(values = c("D" = 16, "T" = 16)) +
  scale_color_manual(values = c("D" = "#009E73", "T" = "#D55E00")) +
  geom_errorbar(aes(ymin  =  yvar - SE, ymax  =  yvar + SE), width =  0.3, size  = 0.4, position=position_dodge(width=0.5)) +
  scale_y_continuous() +
  facet_wrap(~ColorCategory + FruitBiomassCategory,  scales = "free", drop=TRUE) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

ggsave(plot = BiteFreqPlot, file = "BitePlot_narrow.pdf", width = 8, height = 12)

```

###NUTRITIONAL INTAKE ANALYSIS

```{r}

#Reading in csv
df_nutrition_read <- read.csv("Complete_Nutrition_DF_Jul1_2022.csv")



###Modelling gram intake of crude protein
ProteinIntakeModel <- glmer(CP_intake ~  
                                Phenotype*FruitBiomassCategory + 
                                DominanceCategory + 
                                offset(log(Duration)) +
                                (1 | Animal) +
                                (1 | Pair),
                              data = df_nutrition_read, family = Gamma(link="log"), control = glmerControl(optCtrl = list(maxfun = 1500000)))

#Getting model summary
summary(ProteinIntakeModel)

#Planned pairwise comparisons
ProteinInteraction.emm <- emmeans(ProteinIntakeModel, pairwise ~ Phenotype | FruitBiomassCategory, type = "response", adjust = "tukey")

#Putting EMMs in df for plotting
ProteinInteractionPlot <- emmip(ProteinIntakeModel, ~ Phenotype | FruitBiomassCategory, type = "response", plotit = FALSE) 


###Modelling gram intake of water soluble carbohydrates
WSCIntakeModel <- glmer(WSC_intake ~  
                                Phenotype*FruitBiomassCategory + 
                                DominanceCategory + 
                                offset(log(Duration)) +
                                (1 | Animal) +
                                (1 | Pair),
                              data = df_nutrition_read, family = Gamma(link="log"), control = glmerControl(optCtrl = list(maxfun = 1500000)))

#Getting model summary
summary(WSCIntakeModel)

#Planned pairwise comparisons
WSC.emm <- emmeans(WSCIntakeModel, pairwise ~ Phenotype | FruitBiomassCategory, type = "response", adjust = "tukey")

#Putting EMMs in df for plotting
WSCInteractionPlot <- emmip(WSCIntakeModel, ~ Phenotype | FruitBiomassCategory, type = "response", plotit=FALSE) 


#Modelling gram intake of fiber
NDFIntakeModel <- glmer(NDF_intake ~  
                                Phenotype*FruitBiomassCategory + 
                                DominanceCategory + 
                                offset(log(Duration)) +
                                (1 | Animal) +
                                (1 | Pair),
                              data = df_nutrition_read, family = Gamma(link="log"), control = glmerControl(optCtrl = list(maxfun = 1500000)))

#Getting model summary
summary(NDFIntakeModel)

#Planned pairwise comparisons of EMMs
NDF.emm <- emmeans(NDFIntakeModel, pairwise ~ Phenotype | FruitBiomassCategory, type = "response", adjust = "tukey")

#Putting EMMs in df for plotting
NDFIntakePlot <- emmip(NDFIntakeModel, ~ Phenotype | FruitBiomassCategory, type = "response", plotit=FALSE) 



###Plotting EMMs for each model


#Protein plot
CPPlot <- ggplot(ProteinInteractionPlot, aes(x = Phenotype, y = yvar,  color = Phenotype)) +
  geom_point(size = 3) +
  geom_point(data = df_nutrition_read, aes(x = Phenotype, y = CP_intake, color = Phenotype), alpha = 0.2, position = "jitter") +
  scale_shape_manual(values = c("D" = 16, "T" = 16)) +
  scale_color_manual(values = c("D" = "#009E73", "T" = "#D55E00")) +
  geom_errorbar(aes(ymin  =  yvar - SE, ymax  =  yvar + SE), width =  0.2, size  =  0.7) +
  scale_y_continuous() +
  scale_x_discrete(limits = c("D", "T")) +
  ggtitle("Crude protein intake (g)") +
  ylab("Grams of nutrient (EMM)") +
  facet_wrap(~FruitBiomassCategory) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(axis.text.y = element_text(size = 10, color = "black")) +
  theme(axis.text.x = element_blank()) +
  theme(axis.ticks = element_blank()) +
  theme(axis.title.y = element_text(size = 12, color = "black"), axis.title.x = element_blank()) +
  theme(legend.position = "none")


#Carbohydrate plot

WSCPlot <- ggplot(WSCInteractionPlot, aes(x = Phenotype, y = yvar,  color = Phenotype)) +
  geom_point(size = 3) +
   geom_point(data = df_nutrition_read, aes(x = Phenotype, y = WSC_intake, color = Phenotype), alpha = 0.2, position = "jitter") +
  scale_shape_manual(values = c("D" = 16, "T" = 16)) +
  scale_color_manual(values = c("D" = "#009E73", "T" = "#D55E00")) +
  geom_errorbar(aes(ymin  =  yvar - SE, ymax  =  yvar + SE), width =  0.2, size  =  0.7) +
  ylim(0, 30) +
  #scale_y_continuous() +
  scale_x_discrete(limits = c("D", "T")) +
  ggtitle("Water-soluble carbohydrate intake (g)") +
  facet_wrap(~FruitBiomassCategory) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(axis.text.y = element_text(size = 10, color = "black")) +
  theme(axis.text.x = element_blank()) +
  theme(axis.ticks = element_blank()) +
  theme(axis.title.y = element_blank(), axis.title.x = element_blank()) +
  theme(legend.position = "none")

#Fiber plot
NDFPlot <- ggplot(NDFIntakePlot, aes(x = Phenotype, y = yvar,  color = Phenotype)) +
  geom_point(size = 3) +
  geom_point(data = df_nutrition_read, aes(x = Phenotype, y = CP_intake, color = Phenotype), alpha = 0.2, position = "jitter") +
  scale_shape_manual(values = c("D" = 16, "T" = 16)) +
  scale_color_manual(values = c("D" = "#009E73", "T" = "#D55E00")) +
  geom_errorbar(aes(ymin  =  yvar - SE, ymax  =  yvar + SE), width =  0.2, size  = 0.7) +
  scale_y_continuous() +
  scale_x_discrete(limits = c("D", "T")) +
  ggtitle("Neutral detergent fiber intake (g)") +
  facet_wrap(~FruitBiomassCategory) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(axis.text.y = element_text(size = 10, color = "black")) +
  theme(axis.text.x = element_blank()) +
  theme(axis.ticks = element_blank()) +
  theme(axis.title.y = element_blank(), axis.title.x = element_blank()) +
  theme(legend.position = "none") 

#Combining plots
nutritional_intake_plot <- ggarrange(CPPlot, WSCPlot, NDFPlot,  nrow=1, common.legend = TRUE, legend="bottom")

ggsave(plot = nutritional_intake_plot, file = "Fig_3_final.pdf", width = 12, height = 4)


```


###MAKING FIGURE 1
```{r}
###MAKING FIGURE 1

biomass_taxon <- read.csv("FruitBiomassByTaxon.csv")

biomass_taxon <- biomass_taxon %>%
              rename(Taxon = SpeciesCode)
biomass_taxon <- biomass_taxon %>% dplyr::select(-X) 

biomass_summed <- biomass_taxon  %>%
              group_by(ColorCategory, month_of, FruitAbundanceCategory) %>%
              summarise(MonthlyBiomass = sum(biomass_monthly_kg))


biomass_color_plot <- ggplot(biomass_summed, aes(fill = ColorCategory, y = MonthlyBiomass, x = FruitAbundanceCategory)) + geom_boxplot() + 
scale_fill_manual(values = c("con" = "#E59989", "con_both" = "#f2cd78", "cry" ="#DAF7A6", "dark" = "#B994E0")) +
labs(y = "Monthly Fruit Biomass (kg/ha)") +
theme_classic() +
theme(legend.position = "right")

ggsave(plot = biomass_color_plot, file = "biomass_color_plot.pdf", width = 6, height = 4, units = "in")

```

###MAKING FIGURE S1
```{r}
###MAKING FIGURE S1

###PLOTTING PROPORTION OF BITES
df_bite_percent <- df_bite_final %>% mutate(TaxonFruit = case_when(State == "FFR" & Taxon == "FCOT" ~ "con", 
                                      State == "FFR" & Taxon == "GMAC" ~ "con", State == "FFR" & Taxon == "BPOL" ~ "con", State == "FFR" & Taxon == "GAME" ~ "con_both", State == "FFR" & Taxon == "SOBO" ~ "con_both", State == "FFR" & Taxon == "PPLA" ~ "con_both", State == "FFR" & Taxon == "MTIN" ~ "cry", State == "FFR" & Taxon == "QOLE" ~ "cry", State == "FFR" & Taxon == "CVER" ~ "dark",
                                      TRUE ~ State))

bites <- df_bite_percent %>%
              group_by(Phenotype, FruitBiomassCategory, TaxonFruit) %>%
              summarise(Total = sum(Count))

bites_complete <- bites %>% spread(TaxonFruit, Total)
bites_complete[is.na(bites_complete)] <- 0

bites_complete1 <- bites_complete %>% mutate(DM_Total = EFI + FIN + con + con_both + dark + cry)

bites_complete1 <- bites_complete1 %>% mutate(Con_percent = (con/DM_Total)*100)
bites_complete1 <- bites_complete1 %>% mutate(EFI_percent = (EFI/DM_Total)*100)
bites_complete1 <- bites_complete1 %>% mutate(FIN_percent = (FIN/DM_Total)*100)
bites_complete1 <- bites_complete1 %>% mutate(Con_Both_percent = (con_both/DM_Total)*100)
bites_complete1 <- bites_complete1 %>% mutate(Dark_percent = (dark/DM_Total)*100)
bites_complete1 <- bites_complete1 %>% mutate(Cry_percent = (cry/DM_Total)*100)


bite_percent <- bites_complete1 %>% gather("Food", "Percent", Con_percent:Cry_percent)

bite_percent$Food <- as.factor(bite_percent$Food)

bite_percent$Food <- factor(bite_percent$Food, levels = c("Con_percent", "Con_Both_percent", "Cry_percent", "Dark_percent", "EFI_percent", "FIN_percent"))

bite_percent_plot <- ggplot(bite_percent, aes(fill=Food, y=Percent, x = Phenotype)) + 
    geom_bar(alpha = 0.95, position="fill", stat="identity") +
   scale_fill_manual(values=c("#eaab1e","#f2cd78", "#f7dda5", "#fbeed2", "#704990", "#4c1b74")) +
   facet_grid(. ~ FruitBiomassCategory) +
   theme_bw()

ggsave(plot = bite_percent_plot, file = "bite_percent_plot.pdf", width = 6, height = 4, units = "in")




###PLOTTING PROPORTION DRY MATTER INTAKE

df_nutrition <- read.csv("bite_nutrition_table_updated_nov24.csv")
df_bite <- read.csv("bite_query_correct_filtered.csv")
df_pair <- read.csv("pair_ID.csv")
df_biomass <- read.csv("monthly_fruit_biomass.csv")
df_phenotype <- read.csv("focal_phenotypes.csv")

df_bite$DateTime <- parse_date_time(df_bite$DateTime, orders = "mdy")
df_bite <- df_bite %>% mutate(DateTime = as_datetime(DateTime))
df_bite$DateTime <- as.Date(df_bite$DateTime)
df_bite <- df_bite %>% mutate(Month = month(DateTime))


df_bite_nutrition <- df_bite %>% left_join(., df_nutrition, by = c("Taxon" = "Taxon"))


df_bite_nutrition <- df_bite_nutrition %>% left_join(., df_biomass, by = c( 
                                                          "Month" = "Month")) 

df_bite_nutrition <- df_bite_nutrition %>% left_join(., df_phenotype, by = c( 
                                                          "Animal" = "Animal"))                                                        

#Renaming monthly fruit biomass
df_bite_nutrition <- df_bite_nutrition %>%
              rename(MonthlyFruitBiomass = Ripe.Fruit.Biomass)

#Converting to Categorical variable
df_bite_nutrition$FruitBiomassCategory <- if_else(df_bite_nutrition$MonthlyFruitBiomass < 20, "Low","High")

df_bite_nutrition <- df_bite_nutrition[df_bite_nutrition$Taxon == "FCOT" | df_bite_nutrition$Taxon == "QOLE" | df_bite_nutrition$Taxon == "SOBO" | df_bite_nutrition$Taxon == "GAME" | df_bite_nutrition$Taxon == "GMAC" | df_bite_nutrition$Taxon == "PPLA" | df_bite_nutrition$Taxon == "CVER" | df_bite_nutrition$Taxon == "MTIN" | df_bite_nutrition$Taxon == "BPOL" | df_bite_nutrition$Taxon == "INSE" | df_bite_nutrition$Taxon == "CATA" | df_bite_nutrition$Taxon == "LGRA" | df_bite_nutrition$Taxon == "ANTS" | df_bite_nutrition$Taxon == "HIVE" ,]

#Setting NAs to zero
df_bite_nutrition[c("DM.bite", "WM.bite", "CP.bite", "CF.bite", "WSC.bite", "NDF.bite")][is.na(df_bite_nutrition[c("DM.bite", "WM.bite","CP.bite", "CF.bite", "WSC.bite", "NDF.bite")])] <- 0


nut_percent <- df_bite_nutrition  %>% mutate(TaxonFruit = case_when(State == "FFR" & Taxon == "FCOT" ~ "con", 
                                      State == "FFR" & Taxon == "GMAC" ~ "con", State == "FFR" & Taxon == "BPOL" ~ "con", State == "FFR" & Taxon == "GAME" ~ "con_both", State == "FFR" & Taxon == "SOBO" ~ "con_both", State == "FFR" & Taxon == "PPLA" ~ "con_both", State == "FFR" & Taxon == "MTIN" ~ "cry", State == "FFR" & Taxon == "QOLE" ~ "cry", State == "FFR" & Taxon == "CVER" ~ "dark",
                                      TRUE ~ State))



nut_percent <- nut_percent %>%
              group_by(Phenotype, FruitBiomassCategory, TaxonFruit) %>%
              summarise(TotalDM = sum(DM.bite))

nut_percent <- nut_percent %>% spread(TaxonFruit, TotalDM)
nut_percent[is.na(nut_percent)] <- 0

nut_percent <- nut_percent %>% mutate(DM_Total = EFI + FIN + con + con_both + dark + cry)

nut_percent <- nut_percent %>% mutate(Con_percent = (con/DM_Total)*100)
nut_percent <- nut_percent %>% mutate(EFI_percent = (EFI/DM_Total)*100)
nut_percent <- nut_percent %>% mutate(FIN_percent = (FIN/DM_Total)*100)
nut_percent <- nut_percent %>% mutate(Con_Both_percent = (con_both/DM_Total)*100)
nut_percent <- nut_percent %>% mutate(Dark_percent = (dark/DM_Total)*100)
nut_percent <- nut_percent %>% mutate(Cry_percent = (cry/DM_Total)*100)



nut_percent <- nut_percent %>% gather("Food", "Percent", Con_percent:Cry_percent)

nut_percent$Food <- as.factor(nut_percent$Food)

nut_percent$Food <- factor(nut_percent$Food, levels = c("Con_percent", "Con_Both_percent", "Cry_percent", "Dark_percent", "EFI_percent", "FIN_percent"))


nut_percent_plot <- ggplot(nut_percent, aes(fill=Food, y=Percent, x = Phenotype)) + 
    geom_bar(alpha = 0.95, position="fill", stat="identity") +
    scale_fill_manual(values=c("#eaab1e","#f2cd78", "#f7dda5", "#fbeed2", "#704990", "#4c1b74")) +
   facet_grid(. ~ FruitBiomassCategory) +
   theme_bw()


ggsave(plot = nut_percent_plot, file = "nutrition_percent_plot.pdf", width = 6, height = 4, units = "in")



```