---
title: "GLMMs_AmNat"
author: "Allegra DePasquale"
date: "1/4/2021"
output: html_document
---
```{r}
#Library statements

library(sjPlot)
library(anytime)
library(hms)
library(lubridate)
library(tidyverse)
library(fuzzyjoin)
library(lme4)
library(emmeans)
library(lessR)
library(car)
library(ggpubr)
library(viridis)
```
```{r}
#Importing csv files containing behavioral data

df_bite_no_fruit <- read.csv("Bite_Data_no_fruit.csv")
df_bite_fruit <- read.csv("Bite_Data_fruit.csv")
df_nutrition <- read.csv("nutritional_intake_data.csv")

```
```{r}

#GLMM modelling bites of surface-dwelling invertebrates

InvertBiteModel <- glmer(FIN ~  
                                Phenotype*FruitBiomassCategory +
                                offset(log(Duration)) + 
                                (1 | Group/Animal) + 
                                (1 | Pair) + 
                                (1 | DominanceCategory)  +                       
                                (1 | ReproductiveStatus),
                              data = df_bite_no_fruit,
                              family = poisson(link = "log"))  
                              

summary(InvertBiteModel)                             
drop1(InvertBiteModel, test = "Chisq")

Invert.emm <- emmeans(InvertBiteModel, pairwise ~ Phenotype | FruitBiomassCategory, type = "response", adjust = "tukey")

#GLMM modelling bites of conspicuous fruits (those conspicuous to trichromats only)

ConFruitBiteModel <- glmer(con ~  
                                Phenotype*FruitBiomassCategory +
                                offset(log(Duration)) + 
                                (1 | Group/Animal)  +
                                (1 | Pair) + 
                                (1 | DominanceCategory)  +                     
                                (1 | ReproductiveStatus),
                              data = df_bite_fruit,
                              family = poisson(link = "log"), control = glmerControl(optCtrl = list(maxfun = 1500000)))
                                
drop1(ConFruitBiteModel, test = "Chisq")

ConBite.emm <- emmeans(ConFruitBiteModel, pairwise ~ Phenotype | FruitBiomassCategory, type = "response", adjust = "tukey")


#GLMM modelling intake in grams of protein

ProteinIntakeModel <- glmer(CP_intake ~  
                                Phenotype*FruitBiomassCategory + 
                                offset(log(DryMassTotal)) + 
                                (1 | Group/Animal) +
                                (1 | Pair) + 
                                (1 | DominanceCategory)   +                                                          (1 | ReproductiveStatus),
                              data = df_nutrition, family = Gamma(link="log"), control = glmerControl(optCtrl = list(maxfun = 1500000)))



drop1(ProteinIntakeModel, test = "Chisq")

ProteinInteraction.emm <- emmeans(ProteinIntakeModel, pairwise ~ Phenotype | FruitBiomassCategory, type = "response", adjust = "tukey")

#GLMM modelling intake in grams of water soluble carbs (i.e., sugars)

WSCIntakeModel <- glmer(WSC_intake ~  
                                Phenotype*FruitBiomassCategory + 
                                offset(log(DryMassTotal)) + 
                                (1 | Group/Animal) +
                                (1 | Pair) +
                                (1 | DominanceCategory) +
                                (1 | ReproductiveStatus),
                              data = df_nutrition, family = Gamma(link="log"), control = glmerControl(optCtrl = list(maxfun = 1500000)))



drop1(WSCIntakeModel, test = "Chisq")

WSC.emm <- emmeans(WSCIntakeModel, pairwise ~ Phenotype | FruitBiomassCategory, type = "response", adjust = "tukey")


#GLMM modelling intake in grams of neutral detergent fiber

NDFIntakeModel <- glmer(NDF_intake ~  
                                Phenotype*FruitBiomassCategory + 
                                offset(log(DryMassTotal)) + 
                                (1 | Group/Animal) +
                                (1 | Pair) +
                                (1 | DominanceCategory) +
                                (1 | ReproductiveStatus),
                              data = df_nutrition, family = Gamma(link="log"), control = glmerControl(optCtrl = list(maxfun = 1500000)))



drop1(NDFIntakeModel, test = "Chisq")
NDF.emm <- emmeans(NDFIntakeModel, pairwise ~ Phenotype | FruitBiomassCategory, type = "response", adjust = "tukey")

```

