---
title: "NutritionalAnalysis"
author: "Allegra DePasquale"
date: "6/30/2020"
output: html_document
---

```{r}
#Loading dependencies
install.packages("balancr")
library(anytime)
library(hms)
library(lubridate)
library(tidyverse)
library(fuzzyjoin)
library(lme4)
library(emmeans)
library(lessR)
library(balancr)



#Reading in data files with bite counts, pair ID, group, phenotype info, dominance, reproductive status, weather, fruit biomass, and duration
df_bite <- read.csv("bite_query_correct_filtered.csv")
df_pair <- read.csv("pair_ID.csv")
df_group <- read.csv("group_iD.csv")
df_phenotype <- read.csv("focal_phenotypes.csv")
df_dom <- read.csv("dom_2019.csv")
df_rs <- read.csv("reproductivestatus_2019.csv")
df_weather <- read.csv("Weather_For_Allegra_2019.csv")
df_biomass <- read.csv("monthly_fruit_biomass.csv")
df_duration <- read.csv("Foraging_State_Duration.csv")
df_nutrition <- read.csv("focal_nutrition_table_mock_Updated_july9.csv")

```
```{r}
#Removing DateTime column from the dominance df
df_dom <- df_dom %>%
                      dplyr::select(-DateTime) 


#Renaming month column in df_biomass
df_biomass <- df_biomass %>% 
           rename(
           Month = ï..Month,
   
                         )


#Setting start data and end data in the reproductive status dataframe as date objects
df_rs$StartDate <- parse_date_time(df_rs$StartDate, orders = "mdy")
df_rs <- df_rs %>% mutate(StartDate = as_datetime(StartDate))
df_rs$StartDate <- as.Date(df_rs$StartDate)
df_rs$EndDate <- parse_date_time(df_rs$EndDate, orders = "mdy")
df_rs <- df_rs %>% mutate(EndDate = as_datetime(EndDate))
df_rs$EndDate <- as.Date(df_rs$EndDate)

#Renaming DateTime
df_weather <- df_weather %>% 
           rename(
           DateTime = ï..DateTime,
   
                         )

#Setting DateTime as a date object in df_weather
df_weather$DateTime <- parse_date_time(df_weather$DateTime, orders = "ymd")
df_weather <- df_weather %>% mutate(DateTime = as_datetime(DateTime))
df_weather$DateTime <- as.Date(df_weather$DateTime)

#Changing name of DateTimeBegin to DateTime in bite dataframe
df_bite <- df_bite %>% 
           rename(
           DateTime = DateTimeBegin,
   
                         )


#Setting date time in the bite dataframe as date object
df_bite$DateTime <- parse_date_time(df_bite$DateTime, orders = "mdy")
df_bite <- df_bite %>% mutate(DateTime = as_datetime(DateTime))
df_bite$DateTime <- as.Date(df_bite$DateTime)



#Renaming focal column
df_bite <- df_bite %>% 
           rename(
           Focal = ï..ID,
   
                         )
#Renaming pair column                         
df_pair <- df_pair %>% 
           rename(
           Pair = ï..Pair,
   
                         )
                         
#Renaming animal column
df_phenotype <- df_phenotype %>% 
           rename(
           Animal = ï..Animal,
   
                         )    

#Renaming duration column
df_duration <- df_duration %>% 
           rename(
           Focal = ï..ID,
   
                         )

df_nutrition <- df_nutrition %>% 
           rename(
           Taxon = ï..Taxon,
   
                         )


                         
#Excluding Ducky, setting as data frame, and dropping unused factor levels for df_duration

df_duration <- df_duration[!(df_duration$Animal == "DU") ,]
df_duration <- df_duration[!(df_duration$Focal  == "226") ,]
df_duration<- as.data.frame(df_duration)
df_duration <- droplevels(df_duration)                        
                         
                         
#Subsetting durations to include only foraging
df_foraging_duration <- df_duration[df_duration$State == "FFR" | df_duration$State == "FIN" | df_duration$State == "EFI" | df_duration$State == "FOT" | df_duration$State == "FUN" | df_duration$State == "EFF" | df_duration$State == "FFL", ]                         
#Setting duration as seconds
df_foraging_duration$Duration <- lubridate::hms(df_foraging_duration$Duration)
df_foraging_duration$Duration <- as.numeric(df_foraging_duration$Duration)

df_duration$Duration <- lubridate::hms(df_duration$Duration)
df_duration$Duration <- as.numeric(df_duration$Duration)

df_duration <- df_duration[df_duration$State != "OOS", ]  
#Summing duration for every foraging state per focal, and storing as new variable, "Duration"
df_foraging_summed <- df_foraging_duration %>% 
  group_by(Focal, Animal) %>%
  summarise(Duration = sum(Duration))


df_duration_summed <- df_duration %>% 
  group_by(Focal, Animal) %>%
  summarise(Duration = sum(Duration))


```

```{r}
#Joining nutrition df to bite df
df_bite_nutrition <- df_bite %>% left_join(., df_nutrition, by = c("Taxon" = "Taxon" 
                                                            ))

#Setting NAs to zero
df_bite_nutrition[c("CP_bite", "CF_bite", "WSC_bite", "NDF_bite")][is.na(df_bite_nutrition[c("CP_bite", "CF_bite", "WSC_bite", "NDF_bite")])] <- 0

#Grouping by focal, animal, and datetime, and summing cp, cf, wsc, and ndf intake per focal
df_bite_nutrition1 <- df_bite_nutrition %>%
              group_by(Focal, Animal, DateTime) %>%
              summarise(
                        CP_intake = sum(CP_bite),
                        CF_intake = sum(CF_bite),
                        WSC_intake = sum(WSC_bite),
                        NDF_intake = sum(NDF_bite))

```



``` {r}
#Joining duration column to bite data frame
df_joined <- df_foraging_summed %>% left_join(., df_bite_nutrition1, by = c("Focal" = "Focal", 
                                                            "Animal" = "Animal"))
#Joining focal pair id to bite data frame                                                            
df_joined <- df_pair %>% left_join(., df_joined, by = c( 
                                                            "Animal" = "Animal"))                                   
#Joining group info to bite data frame
df_joined <- df_group %>% left_join(., df_joined, by = c( 
                                                            "Animal" = "Animal"))               
#Joining color vision phenotype data to bite dataframe                                  
df_joined <- df_phenotype %>% left_join(., df_joined, by = c( 
                                                            "Animal" = "Animal")) 
                                                            
#Joining dominance data to bite dataframe                                                           
df_joined <- df_dom %>% left_join(., df_joined, by = c( 
                                                            "Animal" = "Animal"))    

                                                       
#Converting dominance ranks to ordinal variable with levels low, mid, and high                                                       
df_joined$DominanceCategory <- if_else(df_joined$Scaled.Rank <= 0.33, "low", if_else(df_joined$Scaled.Rank > 0.33 & df_joined$Scaled.Rank <= 0.66, "mid","high"))                                                            
      
                                                            
#Fuzzy left joining reproductive status to behavioral data
df_joined  <- df_joined %>%
            fuzzy_left_join(., df_rs, by = c("Animal" = "Animal", "DateTime" = "StartDate", "DateTime" = "EndDate"), match_fun = list(`==`, `>=`, `<=`))            
            
#Getting rid of extra columns from the fuzzy left join
 df_joined <- df_joined %>%
                      dplyr::select(-Animal.y, -StartDate, -EndDate)            
            
#Renaming animal
df_joined <- df_joined %>%
              rename(Animal = Animal.x)                                             


#Renaming reproductive status
df_joined <- df_joined %>%
              rename(ReproductiveStatus = Reproductive.Status)
              
#Removing one focal where the tablet wasn't recording seconds, causing a 0 duration, which messes up the offset in the models

df_joined <- df_joined %>% 
            filter(Duration > 0)
            
#Joining weather variables to final df
df_joined <- df_joined %>% left_join(., df_weather, by = c( 
                                                         "DateTime" = "DateTime")) 
                                                         
#Adding month column to final_df to facilitate join with df_biomass
df_joined <- df_joined %>% mutate(Month = month(DateTime))
df_joined <- df_joined %>% left_join(., df_biomass, by = c( 
                                                          "Month" = "Month"))  
                                                          

#Renaming monthly fruit biomass
df_joined <- df_joined %>%
              rename(MonthlyFruitBiomass = Ripe.Fruit.Biomass)

#Z-transforming TempMax, TempMin, Rainfall, and Monthly Fruit Biomass
df_joined  <- df_joined %>%
       mutate_at(vars("TempMax", "TempMin", "Rain", "MonthlyFruitBiomass"), list(~as.numeric(scale(.))))

```
```{r}
#Creating columns for energetic contributions (in kcal) of protein (*4), fiber (*4), fat (*9), and carbohydrates (*4)
df_atwater <- df_joined %>% mutate(PE_Intake = CP_intake * 4)  
df_atwater <- df_atwater %>% mutate(NDF_Energy_Intake = NDF_intake * 4)
df_atwater <- df_atwater %>% mutate(CF_Energy_Intake = CF_intake * 9)
df_atwater <- df_atwater %>% mutate(WSC_Energy_Intake = WSC_intake * 4)

#Creating nonprotein energy column
df_atwater <- df_atwater %>% mutate(NPE_Intake = CF_Energy_Intake + WSC_Energy_Intake + NDF_Energy_Intake)

#Creating column for ratio of NPE:PE
df_atwater <- df_atwater %>% mutate(NPE_PE_Ratio = NPE_Intake / PE_Intake)

#Creating columns for usage in RMTs
df_atwater <- df_atwater %>% mutate(ME_Total = PE_Intake + CF_Energy_Intake + WSC_Energy_Intake)
df_rmt <- df_atwater %>% mutate(ME_Total = PE_Intake + CF_Energy_Intake + WSC_Energy_Intake)

df_rmt <- df_rmt %>% mutate(PE_Percent = (PE_Intake/ME_Total)*100)
df_rmt <- df_rmt %>% mutate(CF_Percent = (CF_Energy_Intake/ME_Total)*100)
df_rmt <- df_rmt %>% mutate(WSC_Percent = (WSC_Energy_Intake/ME_Total)*100)

#Removing unnecessary columns from df_rmt

#Getting rid of extra columns from the fuzzy left join
df_rmt <- df_rmt %>%
                      dplyr::select(-Group, -DominanceCategory, -Duration, -Scaled.Rank, -TempMax, -TempMin, -Rain, -MonthlyFruitBiomass)    

df_rmt$Pair <- as.factor(df_rmt$Pair)
```


####GLMMS WITH GAMMA DISTRIBUTION####

``` {r}

#GLMMs with gamma distribution

#modelling crude protein intake (g)
ProteinIntakeModel <- glmer(CP_intake ~  
                                Phenotype + 
                                DominanceCategory +
                                ReproductiveStatus +
                                TempMax +
                                TempMin +
                                Rain +
                                MonthlyFruitBiomass +
                                offset(log(Duration)) + 
                                (1 | Group/Animal) + (1 | Pair),
                              data = df_atwater, family = Gamma(link="log"), control = glmerControl(optCtrl = list(maxfun = 1500000)))

drop1(ProteinIntakeModel, test = "Chisq")

ProteinIntakeModel.emm <- emmeans(ProteinIntakeModel, "Phenotype", type = "response", adjust = "tukey") #This function displays the LSM

pairs(emmeans(ProteinIntakeModel, "Phenotype", adjust = "tukey"))


#PE intake glmm (kCal)
ProteinEnergyIntakeModel <- glmer(PE_Intake ~  
                                Phenotype + 
                                DominanceCategory +
                                ReproductiveStatus +
                                TempMax +
                                TempMin +
                                Rain +
                                MonthlyFruitBiomass +
                                offset(log(Duration)) + 
                                (1 | Group/Animal) + (1 | Pair),
                              data = df_atwater, nAGQ=0, family = Gamma(link="log"), control = glmerControl(optCtrl = list(maxfun = 1500000)))


ProteinEnergyIntakeModel <- glmer(PE_Intake ~  
                                Phenotype + 
                                DominanceCategory +
                                ReproductiveStatus +
                                TempMax +
                                TempMin +
                                Rain +
                                MonthlyFruitBiomass +
                                offset(ME_Total) + 
                                (1 | Group/Animal) + (1 | Pair),
                              data = df_atwater, nAGQ=0, family = Gamma(link="log"), control = glmerControl(optCtrl = list(maxfun = 1500000)))









drop1(ProteinEnergyIntakeModel, test = "Chisq")

ProteinEnergyIntakeModel.emm <- emmeans(ProteinEnergyIntakeModel, "Phenotype", type = "response", adjust = "tukey") #This function displays the LSM


pairs(emmeans(ProteinEnergyIntakeModel, "Phenotype", adjust = "tukey"))



#WSC intake glmm (g)
WSCIntakeModel <- glmer(WSC_intake ~  
                                Phenotype + 
                                DominanceCategory +
                                ReproductiveStatus +
                                TempMax +
                                TempMin +
                                Rain +
                                MonthlyFruitBiomass +
                                offset(log(Duration)) + 
                                (1 | Group/Animal) + (1 | Pair),
                              data = df_atwater, nAGQ=0, family = Gamma(link="log"), control = glmerControl(optCtrl = list(maxfun = 1500000)))

drop1(WSCIntakeModel, test = "Chisq")

WSCIntakeModel.emm <- emmeans(WSCIntakeModel, "Phenotype", type = "response", adjust = "tukey") #This function displays the LSM

pairs(emmeans(WSCIntakeModel, "Phenotype", adjust = "tukey"))


#modelling nonprotein energy intake (kCal)
NPEIntakeModel <- glmer(NPE_Intake ~  
                                Phenotype + 
                                DominanceCategory +
                                ReproductiveStatus +
                                TempMax +
                                TempMin +
                                Rain +
                                MonthlyFruitBiomass +
                                offset(log(Duration)) + 
                                (1 | Group/Animal) + (1 | Pair),
                              data = df_atwater, nAGQ=0, family = Gamma(link="log"), control = glmerControl(optCtrl = list(maxfun = 1500000)))

drop1(NPEIntakeModel, test = "Chisq")

NPEIntakeModel.emm <- emmeans(NPEIntakeModel, "Phenotype", type = "response", adjust = "tukey") #This function displays the LSM

pairs(emmeans(NPEIntakeModel, "Phenotype", adjust = "tukey"))


#Modelling NPE_PE ratio
RatioModel <- glmer(NPE_PE_Ratio ~  
                                Phenotype + 
                                DominanceCategory +
                                ReproductiveStatus +
                                TempMax +
                                TempMin +
                                Rain +
                                MonthlyFruitBiomass +
                                offset(log(Duration)) + 
                                (1 | Group/Animal) + (1 | Pair),
                              data = df_atwater, nAGQ=0, family = Gamma(link="log"), control = glmerControl(optCtrl = list(maxfun = 1500000)))
drop1(RatioModel, test = "Chisq")

#Modelling wsc energy intake (kCal)
WSCEI <- glmer(WSC_Energy_Intake ~  
                                Phenotype + 
                                DominanceCategory +
                                ReproductiveStatus +
                                TempMax +
                                TempMin +
                                Rain +
                                MonthlyFruitBiomass +
                                offset(log(ForagingDuration)) + 
                                (1 | Group/Animal) + (1 | Pair),
                              data = df_complete, nAGQ=0, family = Gamma(link="log"), control = glmerControl(optCtrl = list(maxfun = 1500000)))

drop1(WSCEI, test = "Chisq")

WSCEI.emm <- emmeans(WSCEI, "Phenotype", type = "response", adjust = "tukey") #This function displays the LSM

pairs(emmeans(WSCEI, "Phenotype", adjust = "tukey"))


```

#####LINEAR MIXED MODELS#####

``` {r}

#Linear mixed models with log transformed response variable

#Crude protein intake model (g)

ProteinIntakeLM<- lmer(log(CP_intake) ~  
                                Phenotype + 
                                DominanceCategory +
                                ReproductiveStatus +
                                TempMax +
                                TempMin +
                                Rain +
                                MonthlyFruitBiomass +
                                offset(log(Duration)) + 
                                (1 | Group/Animal) + (1 | Pair),
                              data = df_atwater,
                              control = lmerControl(optCtrl = list(maxfun = 1500000)))

drop1(ProteinIntakeLM, test = "Chisq")


ProteinIntakeLM.emm <- emmeans(ProteinIntakeLM, "Phenotype", type = "response", adjust = "tukey") #This function displays the LSM


pairs(emmeans(ProteinIntakeLM, "Phenotype", adjust = "tukey"))


#Protein energy intake model (kCal)

PEIntakeLM <- lmer(log(PE_Intake) ~  
                              Phenotype + 
                              DominanceCategory +
                              ReproductiveStatus +
                              TempMax +
                              TempMin +
                              Rain +
                                MonthlyFruitBiomass +
                                offset(log(Duration)) + 
                                (1 | Group/Animal) + (1 | Pair),
                              data = df_atwater,
                              control = lmerControl(optCtrl = list(maxfun = 1500000)))

drop1(PEIntakeLM, test = "Chisq")
PEIntakeLM.emm <- emmeans(PEIntakeLM, "Phenotype", type = "response", adjust = "tukey") #This function displays the LSM


pairs(emmeans(PEIntakeLM, "Phenotype", adjust = "tukey"))

#Water soluble carbs intake model (g)

WSCIntakeLM <- lmer(log(WSC_intake) ~  
                                Phenotype + 
                                DominanceCategory +
                                ReproductiveStatus +
                                TempMax +
                                TempMin +
                                Rain +
                                MonthlyFruitBiomass +
                                offset(log(Duration)) + 
                                (1 | Group/Animal) + (1 | Pair),
                              data = df_atwater,
                              control = lmerControl( optCtrl = list(maxfun = 1500000)))
drop1(WSCIntakeLM, test = "Chisq")
WSCIntakeLM.emm <- emmeans(WSCIntakeLM, "Phenotype", type = "response", adjust = "tukey") #This function displays the LSM


pairs(emmeans(WSCIntakeLM, "Phenotype", adjust = "tukey"))

#WSC energy intake model (kCal)

WSCEIntakeLM <- lmer(log(WSC_Energy_Intake) ~  
                                Phenotype + 
                                DominanceCategory +
                                ReproductiveStatus +
                                TempMax +
                                TempMin +
                                Rain +
                                MonthlyFruitBiomass +
                                offset(log(Duration)) + 
                                (1 | Group/Animal) + (1 | Pair),
                              data = df_atwater,
                              control = lmerControl( optCtrl = list(maxfun = 1500000)))


drop1(WSCEIntakeLM, test = "Chisq")
WSCEIntakeLM.emm <- emmeans(WSCEIntakeLM, "Phenotype", type = "response", adjust = "tukey") 


pairs(emmeans(WSCEIntakeLM, "Phenotype", adjust = "tukey"))




NPEIntakeLM <- lmer(log(NPE_Intake) ~  
                                Phenotype + 
                                DominanceCategory +
                                ReproductiveStatus +
                                TempMax +
                                TempMin +
                                Rain +
                                MonthlyFruitBiomass +
                                offset(log(Duration)) + 
                                (1 | Group/Animal) + (1 | Pair),
                              data = df_atwater,
                              control = lmerControl( optCtrl = list(maxfun = 1500000)))

drop1(NPEIntakeLM, test = "Chisq")
NPEIntakeLM.emm <- emmeans(NPEIntakeLM, "Phenotype", type = "response", adjust = "tukey") #This function displays the LSM


pairs(emmeans(NPEIntakeLM, "Phenotype", adjust = "tukey"))

```


#PLOTTING 

```{r}
plots 

#Scatterplot of npe intake versus pe intake
ggplot(df_atwater, aes(y = NPE_Intake, x = PE_Intake, color = Phenotype)) + 
    geom_point() +
    geom_smooth(method=lm) +
    xlab("NPE Intake (kCal)") + ylab("Protein Energy Intake (kCal)") +
     theme_classic() +
     theme(axis.title.x= element_text(size = 12, color = "black")) +
        theme(legend.position = "bottom")

ggplot(df_atwater, aes(y = PE_Intake, x = DateTime, color = Phenotype)) + 
    geom_point() +
    geom_smooth(method=lm) +
    xlab("DateTime") + ylab("Protein Energy Intake (kCal)") +
     theme_classic() +
     theme(axis.title.x= element_text(size = 12, color = "black")) +
        theme(legend.position = "bottom")

ggplot(df_atwater, aes(y = NPE_Intake, x = DateTime, color = Phenotype)) + 
    geom_point() +
    geom_smooth(method=lm) +
    xlab("DateTime") + ylab("Non-protein Energy Intake (kCal)") +
     theme_classic() +
     theme(axis.title.x= element_text(size = 12, color = "black")) +
        theme(legend.position = "bottom")




#Plotting WSC energy intake emmeans

WSCEI.emm.cld.tukey <- cld.emmGrid(WSCEI.emm, alpha = 0.05, Letters = letters, adjust = "tukey") #This function creates a compact letter display of the LSM enabling use with ggplot. It also adds a Tukey adjustment to test for honest significant difference between the means.


WSCE <- WSCEI.emm.cld.tukey #Renaming CLD object for increased ease with plotting.

WSCEPlot <- ggplot(WSCE, aes(x = Phenotype, y = response, shape = Phenotype, color = Phenotype)) +
  geom_point(size = 3) +
  scale_shape_manual(values = c("D" = 16, "T" = 16)) +
  scale_color_manual(values = c("D" = "#0072B2", "T" = "#E69F00")) +
  geom_errorbar(aes(ymin  =  response - SE, ymax  =  response + SE), width =  0.2, size  =  0.7) +
  scale_y_continuous(limits = c(10,30)) +
  scale_x_discrete(limits = c("D", "T")) +
  ggtitle("Water-soluble carbohydrate energy intake per focal (kCal)") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(axis.text.y = element_text(size = 15, color = "black")) +
  theme(axis.text.x = element_blank()) +
  theme(axis.ticks = element_blank()) +
  theme(axis.title.y = element_blank(), axis.title.x = element_blank()) +
  theme(legend.position = "bottom")


#Plotting nonprotein energy intake emmeans

NPE.emm.cld.tukey <- cld.emmGrid(NPEIntakeModel.emm, alpha = 0.05, Letters = letters, adjust = "tukey") #This function creates a compact letter display of the LSM enabling use with ggplot. It also adds a Tukey adjustment to test for honest significant difference between the means.


NPE <- NPE.emm.cld.tukey #Renaming CLD object for increased ease with plotting.

NPEPlot <- ggplot(NPE, aes(x = Phenotype, y = response, shape = Phenotype, color = Phenotype)) +
  geom_point(size = 3) +
  scale_shape_manual(values = c("D" = 16, "T" = 16)) +
  scale_color_manual(values = c("D" = "#0072B2", "T" = "#E69F00")) +
  geom_errorbar(aes(ymin  =  response - SE, ymax  =  response + SE), width =  0.2, size  =  0.7) +
  scale_y_continuous(limits = c(40,80)) +
  scale_x_discrete(limits = c("D", "T")) +
  ggtitle("Non-Protein energy intake per Focal (kcal)") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(axis.text.y = element_text(size = 15, color = "black")) +
  theme(axis.text.x = element_blank()) +
  theme(axis.ticks = element_blank()) +
  theme(axis.title.y = element_blank(), axis.title.x = element_blank()) +
  theme(legend.position = "bottom")
  
  
  
#Plotting protein energy intake emmeans
  
PE.emm.cld.tukey <- cld.emmGrid(ProteinEnergyIntakeModel.emm, alpha = 0.05, Letters = letters, adjust = "tukey") #This function creates a compact letter display of the LSM enabling use with ggplot. It also adds a Tukey adjustment to test for honest significant difference between the means.

PE <- PE.emm.cld.tukey #Renaming CLD object for increased ease with plotting.

ProteinEnergyPlot <- ggplot(PE, aes(x = Phenotype, y = response, shape = Phenotype, color = Phenotype)) +
  geom_point(size = 3) +
  scale_shape_manual(values = c("D" = 16, "T" = 16)) +
  scale_color_manual(values = c("D" = "#0072B2", "T" = "#E69F00")) +
  geom_errorbar(aes(ymin  =  response - SE, ymax  =  response + SE), width =  0.2, size  =  0.7) +
  scale_y_continuous(limits = c(10,25)) +
  scale_x_discrete(limits = c("D", "T")) +
  ggtitle("Protein energy intake per Focal (kcal)") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(axis.text.y = element_text(size = 15, color = "black")) +
  theme(axis.text.x = element_blank()) +
  theme(axis.ticks = element_blank()) +
  theme(axis.title.y = element_blank(), axis.title.x = element_blank()) +
  theme(legend.position = "bottom")
  
#RMT of food composition

df_food_rmt <- read.csv("focal_nutrition_table_mock_comp_rmt_reduced.csv")
df_food_rmt <- df_food_rmt %>% 
           rename(
           Taxon = ï..Taxon,
           CPE_Percent = X.CPE,
           CFE_Percent = X.CFE,
           WSCE_Percent = X.WSCE
   
                         )

food_rmt <- ggplot(df_food_rmt, aes(y = CFE_Percent, x = WSCE_Percent, color = FoodType, shape = FoodType)) + 
    geom_point() +
  xlim(0, 100) + ylim (0,100) +
  geom_abline(intercept = 100, slope = -1, linetype = 2) +
    xlab("Water Soluble Carbohydrate %") + ylab("Crude Fat %") +
     theme_classic() +
     theme(axis.title.x= element_text(size = 12, color = "black")) +
        theme(legend.position = "bottom")

#Plotting Intake RMT
intake_rmt <- ggplot(df_rmt, aes(y = CF_Percent, x = WSC_Percent, color = Phenotype)) + 
    geom_point() +
  xlim(0, 100) + ylim (0,100) +
  geom_abline(intercept = 100, slope = -1, linetype = 2) +
    xlab("Water Soluble Carbohydrate %") + ylab("Crude Fat %") +
     theme_classic() +
     theme(axis.title.x= element_text(size = 12, color = "black")) +
        theme(legend.position = "bottom")





```

```{r}
###Just dichromats
df_di <- df_atwater[df_atwater$Phenotype != "T", ]  

df_tri <- df_atwater[df_atwater$Phenotype != "D", ]  




```

