---
title: "RMTs without NDF"
date: "1/4/2021"
output: html_document
---
``` {r}
#Library statements
library(tidyverse)
library(lme4)
library(ggplot2)
library(emmeans)
library(lessR)
library(ggpubr)
library(viridis)

```

###FOOD COMPOSITION RMT
```{r}

#Reading in file
df_food_rmt_no_ndf <- read.csv("food_RMT.csv")


#Renaming Taxon column if this weird special character shows up after import
df_food_rmt_no_ndf <- df_food_rmt_no_ndf %>% 
           rename(
           Taxon = ï..Taxon)

#Building food comp RMT          
food_rmt_no_ndf <- ggplot(df_food_rmt_no_ndf, aes(y = CFE., x = WSCE., color = Food.Type, shape = Food.Type)) + 
    geom_point() +
  xlim(0, 100) + ylim (0,100) +
  geom_abline(intercept = 100, slope = -1, linetype = 2) +
    scale_color_viridis(discrete=TRUE) +
  ggtitle("Nutritional composition of foods") +
    xlab("Water Soluble Carbohydrate %") + ylab("Crude Fat %") +
     theme_classic() +
     theme(plot.title = element_text(size = 12, hjust = 0.5)) +
     theme(axis.title.x= element_text(size = 12, color = "black")) +
        theme(legend.position = "right")

```


###Intake RMTs
```{r}

###Reading in file
df_nutrition <- read.csv("Complete_Nutrition_DF_Jul1_2022.csv")

###Low food abundance RMT


#Subsetting to low fruit months
df_low <-  df_nutrition[df_nutrition$FruitBiomassCategory == "Low",]

#Grouping by animal and averaging each intake variable
df_ind_mean_low <- df_low %>%
              group_by(Animal, Phenotype) %>%
              summarise(
                        Mean_CP_intake = mean(CP_intake),
                        Mean_CF_intake = mean(CF_intake),
                        Mean_WSC_intake = mean(WSC_intake),
                        Mean_NDF_intake = mean(NDF_intake),
                        Mean_Dry_Mass_intake = mean(DryMassTotal))


#Creating columns for macronutrient energy values
df_ind_mean_low <- df_ind_mean_low %>% mutate(Mean_PE_Intake = Mean_CP_intake * 4)  
df_ind_mean_low <- df_ind_mean_low %>% mutate(Mean_NDF_Energy_Intake = Mean_NDF_intake * 4)
df_ind_mean_low <- df_ind_mean_low %>% mutate(Mean_CF_Energy_Intake = Mean_CF_intake * 9)
df_ind_mean_low <- df_ind_mean_low %>% mutate(Mean_WSC_Energy_Intake = Mean_WSC_intake * 4)



#Creating average total metabolizable energy (ME) column
df_rmt_ind_mean_low <- df_ind_mean_low %>% mutate(ME_Total_Mean = Mean_PE_Intake + Mean_CF_Energy_Intake + Mean_WSC_Energy_Intake)



#Calculating sugar percent of ME
df_rmt_ind_mean_low <- df_rmt_ind_mean_low %>% mutate(Mean_WSC_Percent = (Mean_WSC_Energy_Intake/ME_Total_Mean)*100)

#Calculating fat percent of ME
df_rmt_ind_mean_low <- df_rmt_ind_mean_low %>% mutate(Mean_CF_Percent = (Mean_CF_Energy_Intake/ME_Total_Mean)*100)

#Calculating protein percent of ME
df_rmt_ind_mean_low <- df_rmt_ind_mean_low %>% mutate(Mean_PE_Percent = (Mean_PE_Intake/ME_Total_Mean)*100)


#Plotting RMT
mean_ind_intake_rmt_low <- ggplot(df_rmt_ind_mean_low, aes(y = Mean_CF_Percent, x = Mean_WSC_Percent, color = Phenotype)) + 
    geom_point() +
    scale_color_viridis(discrete=TRUE) +
  ggtitle("Mean nutritional intake: low fruit abundance") +
  xlim(0, 100) + ylim (0,100) +
  geom_abline(intercept = 100, slope = -1, linetype = 2) +
    xlab("Water soluble carbohydrates %") + ylab("Crude fat %") +
     theme_classic() +
     theme(plot.title = element_text(size = 12, hjust = 0.5)) +
     theme(axis.title.x= element_text(size = 12, color = "black")) +
        theme(legend.position = "none")
```

```{r}

#High fruit abundance RMT 

#Subsetting to high fruit months only
df_high <-  df_nutrition[df_nutrition$FruitBiomassCategory == "High",]

#Grouping by animal and averaging each intake variable
df_ind_mean_high <- df_high %>%
              group_by(Animal, Phenotype) %>%
              summarise(
                        Mean_CP_intake = mean(CP_intake),
                        Mean_CF_intake = mean(CF_intake),
                        Mean_WSC_intake = mean(WSC_intake),
                        Mean_NDF_intake = mean(NDF_intake),
                        Mean_Dry_Mass_intake = mean(DryMassTotal))

#Creating columns for macronutrient energy values
df_ind_mean_high <- df_ind_mean_high %>% mutate(Mean_PE_Intake = Mean_CP_intake * 4)  
df_ind_mean_high <- df_ind_mean_high %>% mutate(Mean_NDF_Energy_Intake = Mean_NDF_intake * 4)
df_ind_mean_high <- df_ind_mean_high %>% mutate(Mean_CF_Energy_Intake = Mean_CF_intake * 9)
df_ind_mean_high <- df_ind_mean_high %>% mutate(Mean_WSC_Energy_Intake = Mean_WSC_intake * 4)


#Creating average total metabolizable energy (ME) column
df_rmt_ind_mean_high <- df_ind_mean_high %>% mutate(ME_Total_Mean = Mean_PE_Intake + Mean_CF_Energy_Intake + Mean_WSC_Energy_Intake)

#Calculating sugar percent of ME
df_rmt_ind_mean_high <- df_rmt_ind_mean_high %>% mutate(Mean_WSC_Percent = (Mean_WSC_Energy_Intake/ME_Total_Mean)*100)

#Calculating fat percent of ME
df_rmt_ind_mean_high <- df_rmt_ind_mean_high %>% mutate(Mean_CF_Percent = (Mean_CF_Energy_Intake/ME_Total_Mean)*100)

#Calculating protein percent of ME
df_rmt_ind_mean_high <- df_rmt_ind_mean_high %>% mutate(Mean_PE_Percent = (Mean_PE_Intake/ME_Total_Mean)*100)


#Plotting RMT
mean_ind_intake_rmt_high <- ggplot(df_rmt_ind_mean_high, aes(y = Mean_CF_Percent, x = Mean_WSC_Percent, color = Phenotype)) + 
    geom_point() +
    scale_color_viridis(discrete=TRUE) +
  ggtitle("Mean nutritional intake: high fruit abundance") +
  xlim(0, 100) + ylim (0,100) +
  geom_abline(intercept = 100, slope = -1, linetype = 2) +
    xlab("Water soluble carbohydrates %") + ylab("Crude fat %") +
     theme_classic() +
     theme(plot.title = element_text(size = 12, hjust = 0.5)) +
     theme(axis.title.x= element_text(size = 12, color = "black")) +
        theme(legend.position = "none")


plotscombined_rmt <- ggarrange(mean_ind_intake_rmt_high, mean_ind_intake_rmt_low, nrow=1, common.legend = TRUE, legend="bottom")


final_rmt_plot <- ggarrange(food_rmt_no_ndf, plotscombined_rmt, nrow=2, common.legend = FALSE)



```

